#!/usr/bin/env -S node --experimental-strip-types --disable-warning=ExperimentalWarning
//
// A wizard - guides a human through a manual procedure step by step.
// Generated by the wizard skill.
//
// Everything above the "STAGES" marker is the wizard library. Keep it the same
// in every generated wizard. Author the per-step stages below that marker.
//
// Adapted from Matt Pocock's Bash wizard template:
// https://github.com/mattpocock/skills/tree/main/skills/in-progress/wizard

const { existsSync, readFileSync, writeFileSync } = require("node:fs");
const { spawn, spawnSync } = require("node:child_process");
const { createInterface } = require("node:readline/promises");
const { stdin, stdout } = process;

type StageAction = (helpers: WizardHelpers) => Promise<void> | void;

type StageDefinition = {
  title: string;
  minutes: number;
  action: StageAction;
};

type WizardOptions = {
  title: string;
  totalMinutes: number;
  envFile?: string;
};

interface WizardHelpers {
  envFile: string;
  say(message: string): void;
  step(message: string): void;
  note(message: string): void;
  warn(message: string): void;
  openUrl(url: string): Promise<void>;
  pause(message?: string): Promise<void>;
  confirm(question: string): Promise<boolean>;
  ask(key: string, prompt: string): Promise<string>;
  askSecret(key: string, prompt: string): Promise<string>;
  writeEnv(key: string, value: string): void;
  setSecret(name: string, value: string): void;
  setVar(name: string, value: string): void;
}

const useColor = Boolean(stdout.isTTY && process.env.NO_COLOR === undefined);
const colors = {
  bold: "\u001b[1m",
  dim: "\u001b[2m",
  reset: "\u001b[0m",
  blue: "\u001b[34m",
  green: "\u001b[32m",
  yellow: "\u001b[33m",
};

let lineReader: ReturnType<typeof createInterface> | undefined;
const scriptedInput: string[] | undefined = stdin.isTTY
  ? undefined
  : readFileSync(0, "utf8").split(/\r?\n/);
let scriptedInputIndex = 0;

function paint(value: string, color: string): string {
  return useColor ? `${color}${value}${colors.reset}` : value;
}

function clearScreen(): void {
  if (stdout.isTTY) {
    stdout.write("\u001b[2J\u001b[3J\u001b[H");
  }
}

async function readLine(prompt: string): Promise<string> {
  stdout.write(prompt);
  if (scriptedInput !== undefined) {
    return scriptedInput[scriptedInputIndex++] ?? "";
  }

  lineReader ??= createInterface({ input: stdin, output: stdout });
  return lineReader.question("");
}

function closeLineReader(): void {
  lineReader?.close();
  lineReader = undefined;
}

async function readHidden(prompt: string): Promise<string> {
  if (!stdin.isTTY || typeof stdin.setRawMode !== "function") {
    return readLine(prompt);
  }

  closeLineReader();
  stdout.write(prompt);
  stdin.resume();
  stdin.setRawMode(true);

  return new Promise<string>((resolve, reject) => {
    let value = "";

    const cleanup = (): void => {
      stdin.setRawMode?.(false);
      stdin.pause();
      stdin.off("data", onData);
      stdout.write("\n");
    };

    const onData = (chunk: Buffer | string): void => {
      for (const character of chunk.toString()) {
        if (character === "\u0003") {
          cleanup();
          reject(new Error("Interrupted"));
          return;
        }

        if (character === "\r" || character === "\n") {
          cleanup();
          resolve(value);
          return;
        }

        if (character === "\u007f" || character === "\b") {
          value = value.slice(0, -1);
          continue;
        }

        if (character === "\u0015") {
          value = "";
          continue;
        }

        value += character;
      }
    };

    stdin.on("data", onData);
  });
}

function existingValue(envFile: string, key: string): string | undefined {
  if (!existsSync(envFile)) {
    return undefined;
  }

  const prefix = `${key}=`;
  const lines = readFileSync(envFile, "utf8").split(/\r?\n/);
  const line = lines.filter((candidate) => candidate.startsWith(prefix)).at(-1);
  return line === undefined ? undefined : line.slice(prefix.length);
}

function upsertEnv(envFile: string, key: string, value: string): void {
  const current = existsSync(envFile) ? readFileSync(envFile, "utf8") : "";
  const lines = current.split(/\r?\n/);
  if (current.endsWith("\n")) {
    lines.pop();
  }

  const next = lines.filter((line) => !line.startsWith(`${key}=`));
  next.push(`${key}=${value}`);
  writeFileSync(envFile, `${next.join("\n")}\n`, "utf8");
}

async function tryOpen(command: string, args: string[]): Promise<boolean> {
  return new Promise<boolean>((resolve) => {
    let settled = false;
    const settle = (result: boolean): void => {
      if (settled) {
        return;
      }
      settled = true;
      resolve(result);
    };

    const child = spawn(command, args, {
      detached: true,
      stdio: "ignore",
    });
    child.once("error", () => settle(false));
    child.once("spawn", () => {
      child.unref();
      settle(true);
    });
  });
}

async function openBrowser(url: string, warn: (message: string) => void): Promise<void> {
  const candidates: Array<[string, string[]]> = [];

  if (process.env.WSL_DISTRO_NAME) {
    candidates.push(["wslview", [url]], ["explorer.exe", [url]]);
  } else if (process.platform === "darwin") {
    candidates.push(["open", [url]]);
  } else if (process.platform === "win32") {
    candidates.push(["explorer.exe", [url]]);
  } else {
    candidates.push(["xdg-open", [url]], ["gio", ["open", url]]);
  }

  for (const [command, args] of candidates) {
    if (await tryOpen(command, args)) {
      return;
    }
  }

  warn(`Could not open a browser. Visit this URL manually: ${url}`);
}

function ghIsReady(): boolean {
  const result = spawnSync("gh", ["auth", "status"], {
    stdio: "ignore",
  });
  return result.status === 0;
}

function setGithubSecret(name: string, value: string): boolean {
  if (!ghIsReady()) {
    return false;
  }

  const result = spawnSync("gh", ["secret", "set", name], {
    input: value,
    stdio: ["pipe", "ignore", "ignore"],
  });
  return result.status === 0;
}

function setGithubVariable(name: string, value: string): boolean {
  if (!ghIsReady()) {
    return false;
  }

  const result = spawnSync("gh", ["variable", "set", name, "--body", value], {
    stdio: "ignore",
  });
  return result.status === 0;
}

class Wizard {
  stages: StageDefinition[] = [];
  stageIndex = 0;
  minutesElapsed = 0;
  writtenEnv: string[] = [];
  writtenSecrets: string[] = [];
  skipped: string[] = [];
  title: string;
  totalMinutes: number;
  envFile: string;

  constructor(options: WizardOptions) {
    this.title = options.title;
    this.totalMinutes = options.totalMinutes;
    this.envFile = options.envFile ?? process.env.ENV_FILE ?? ".env";
  }

  stage(title: string, minutes: number, action: StageAction): this {
    this.stages.push({ title, minutes, action });
    return this;
  }

  async run(): Promise<void> {
    await this.showBanner();

    for (const definition of this.stages) {
      clearScreen();
      this.stageIndex += 1;
      const remaining = Math.max(0, this.totalMinutes - this.minutesElapsed);
      this.minutesElapsed += definition.minutes;
      console.log(
        `\n${paint(`>> Stage ${this.stageIndex}/${this.stages.length} - ${definition.title}`, colors.bold)} ${paint(`(~${remaining} min left)`, colors.dim)}`,
      );
      await definition.action(this.helpers());
    }

    this.finish();
  }

  private async showBanner(): Promise<void> {
    clearScreen();
    console.log(`\n${paint(this.title, colors.blue)}`);
    console.log(`  ${paint(`${this.stages.length} stages - about ${this.totalMinutes} minutes`, colors.dim)}\n`);
    console.log(`  ${paint("You drive the browser; this wizard tells you what to do and", colors.dim)}`);
    console.log("  captures values you copy back. Stop with Ctrl-C and re-run later; it");
    console.log("  remembers values already saved.");
    await this.helpers().pause("Ready to start? ");
  }

  private helpers(): WizardHelpers {
    return {
      envFile: this.envFile,
      say: (message) => console.log(`  ${message}`),
      step: (message) => console.log(`  ${paint(">", colors.blue)} ${message}`),
      note: (message) => console.log(`  ${paint(message, colors.dim)}`),
      warn: (message) => console.log(`  ${paint(`! ${message}`, colors.yellow)}`),
      openUrl: (url) => {
        console.log(`  ${paint("opening", colors.green)} ${url}`);
        return openBrowser(url, (message) => console.log(`  ${paint(`! ${message}`, colors.yellow)}`));
      },
      pause: async (message = "Press Enter to continue") => {
        await readLine(`  ${paint(message, colors.dim)} `);
      },
      confirm: async (question) => {
        const reply = await readLine(`  ${paint(`? ${question} [y/N]`, colors.yellow)} `);
        return /^y/i.test(reply.trim());
      },
      ask: async (key, prompt) => {
        const current = existingValue(this.envFile, key);
        const suffix = current === undefined ? "" : ` ${paint("[Enter keeps current]", colors.dim)}`;
        const answer = await readLine(`  ${paint(prompt, colors.bold)}${suffix} `);
        return answer === "" && current !== undefined ? current : answer;
      },
      askSecret: async (key, prompt) => {
        const current = existingValue(this.envFile, key);
        const suffix = current === undefined ? "" : ` ${paint("[Enter keeps current]", colors.dim)}`;
        const answer = await readHidden(`  ${paint(prompt, colors.bold)}${suffix} `);
        return answer === "" && current !== undefined ? current : answer;
      },
      writeEnv: (key, value) => {
        upsertEnv(this.envFile, key, value);
        this.writtenEnv.push(key);
        console.log(`  ${paint("wrote", colors.green)} ${key} -> ${this.envFile}`);
      },
      setSecret: (name, value) => {
        if (setGithubSecret(name, value)) {
          this.writtenSecrets.push(name);
          console.log(`  ${paint("set", colors.green)} GitHub secret ${name}`);
          return;
        }

        this.skipped.push(`GitHub secret ${name} (set it manually: gh secret set ${name})`);
        console.log(`  ${paint(`! skipped GitHub secret ${name} - gh is not ready`, colors.yellow)}`);
      },
      setVar: (name, value) => {
        if (setGithubVariable(name, value)) {
          console.log(`  ${paint("set", colors.green)} GitHub variable ${name}`);
          return;
        }

        this.skipped.push(`GitHub variable ${name}`);
        console.log(`  ${paint(`! skipped GitHub variable ${name} - gh is not ready`, colors.yellow)}`);
      },
    };
  }

  private finish(): void {
    closeLineReader();
    clearScreen();
    console.log(`\n${paint("Setup complete", colors.green)}`);
    if (this.writtenEnv.length > 0) {
      console.log(`  ${paint(`wrote ${this.writtenEnv.length} value(s) to ${this.envFile}: ${this.writtenEnv.join(", ")}`, colors.dim)}`);
    }
    if (this.writtenSecrets.length > 0) {
      console.log(`  ${paint(`set ${this.writtenSecrets.length} GitHub secret(s): ${this.writtenSecrets.join(", ")}`, colors.dim)}`);
    }
    if (this.skipped.length > 0) {
      console.log(`\n  ${paint("Still to do by hand:", colors.yellow)}`);
      for (const item of this.skipped) {
        console.log(`  ${paint(`- ${item}`, colors.dim)}`);
      }
    }
    console.log();
  }
}

function createWizard(options: WizardOptions): Wizard {
  return new Wizard(options);
}

// -----------------------------------------------------------------------------
// STAGES - author this section. Add one wizard.stage() call per human step.
// -----------------------------------------------------------------------------

async function main(): Promise<void> {
  const wizard = createWizard({
    title: "Stripe setup",
    totalMinutes: 5,
  });

  wizard.stage("Stripe - API keys", 5, async ({ say, openUrl, step, ask, askSecret, writeEnv, setSecret }) => {
    say("We will grab your Stripe test keys and store them for local development and CI.");
    await openUrl("https://dashboard.stripe.com/test/apikeys");
    step("On the API keys page, copy the publishable key (starts pk_test_).");
    const publishableKey = await ask("STRIPE_PUBLISHABLE_KEY", "Publishable key:");
    step("Click Reveal test key on the secret key row, then copy it.");
    const secretKey = await askSecret("STRIPE_SECRET_KEY", "Secret key:");
    writeEnv("STRIPE_PUBLISHABLE_KEY", publishableKey);
    writeEnv("STRIPE_SECRET_KEY", secretKey);
    setSecret("STRIPE_SECRET_KEY", secretKey);
  });

  await wizard.run();
}

main().catch((error: unknown) => {
  closeLineReader();
  const message = error instanceof Error ? error.message : String(error);
  console.error(`\nWizard stopped: ${message}`);
  process.exitCode = message === "Interrupted" ? 130 : 1;
});
